services:
  rss-aggregator:
    image: ghcr.io/sphexi/rss-aggregator:main
    container_name: rss-aggregator
    environment:
      - MAX_ITEMS=50
    ports:
      - "44444:44444"
      - "33333:33333"
    volumes:
      - /path/to/config.json:/app/config:ro
    restart: unless-stopped
